{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "user-service.serviceAccountName" . }}
  labels:
{{ include "user-service.labels" . | indent 4 }}
{{- end -}}
